language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev -o

script:
  - ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/phpmd ./src text design,unusedcode

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
